name: upi_pay_example
description: Demonstrates how to use the upi_pay plugin.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.0

environment:
  sdk: ">=3.5.4"
  flutter: ">=3.24.5"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  upi_pay:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
